name: Release

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/pnpm-setup.yml@main

  release:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/semantic-release.yml@main
    secrets:
      REPO_ACCESSS_TOKEN: ${{ secrets.REPO_ACCESSS_TOKEN }}